### ISSUE TITLE
Undocumented permissions issue

### ISSUE THREAD

**Issue by sofmeright** [SickHub/arkserver#23]
I don't see anything in the documentation but I just wanted to comment for visibility that when I wan the container it struggled with permissions till I did a chown 1001:1001 of all the folders. This is on a ubuntu host running the latest docker compose etc available from the official repo. Great stuff! I love the documentation specifies how to layout folders for cluster etc. This is to replace my current image I was using once I get all the setting and data migrated.

**Comment by sofmeright** [comment]
Hey I wanted to update this ticket with some additional information that I feel can improve the deployment experience for other users. I recently found a solution that can be used to push the permission changes within the docker compose and wanted to contribute the solution for others to use as well!

```
services:

  change-vol-ownership:
    image: ubuntu
    user: root
    volumes:
      - /mnt/app_data/Server/_docker_stack/ark-se:/ark-se
    command: >
      bash -c "
      chown -R 1001:1001 /ark-se"
  
  ark-se-tmc-antartika:
    restart: unless-stopped
    depends_on:
      change-vol-ownership:
        condition: service_completed_successfully
    image: drpsychick/arkserver:latest
    tty: true
    stdin_open: true
    container_name: ark-se-tmc-antartika
    environment:
      - am_arkNoPortDecrement=true
      # Map Names: TheIsland, TheCenter, ScorchedEarth_P, Ragnarok, Aberration_P, Extinction, Valguero_P, Genesis, CrystalIsles, Gen2, LostIsland, Fjordur
      - am_ark_SessionName=<ServerFlaire>-Antartika
      - am_serverMap=antartika
      - am_ark_ServerAdminPassword=<redacted>
      - am_ark_ServerPassword=<redacted>
      - am_ark_MaxPlayers=10
      - am_ark_QueryPort=27059
      - am_ark_Port=7778
      - am_ark_RCONPort=27097
      #am_arkwarnminutes=15
      - am_arkAutoUpdateOnStart=false # only do it on the first one?
      - am_ark_GameModIds=1213429840,1232362083,1565015734,1609138312,1840761213,506506101,731604991,751991809,793605978,806480270,821530042,895711211,902616446,924933745,946379571
      - ARKCLUSTER=true
      # this must be unique across all clusters on steam!
      - am_arkopt_clusterid=<redacted>
      #- am_arkflag_NoTransferFromFiltering=
      - am_arkflag_ForceAllowCaveFlyers=true
      - am_arkflag_crossplay=true
      - ARKSERVER_SHARED=/arkserver
      #- VALIDATE_SAVE_EXISTS=false
      #- BACKUP_ONSTART=false
      #- LOG_RCONCHAT=0
    volumes:
      - /mnt/app_data/Server/_docker_stack/ark-se/TMC/antartika:/ark
      - /mnt/app_data/Server/_docker_stack/ark-se/TMC/antartika/saved:/arkserver/ShooterGame/Saved
      - /mnt/app_data/Server/_docker_stack/ark-se/arkclusters:/arkserver/ShooterGame/Saved/clusters
      - /mnt/app_data/Server/_docker_stack/ark-se/arkserver:/arkserver
      #- /ark/config/GameUserSettings.ini /ark/config/Game.ini
    ports:
     - 7778:7778/udp
     - 7778:7778
     - 27059:27059/udp
     - 27059:27059
     - 27097:27097
    #ulimits:
      #nofile:
        #soft: 1000000
        #hard: 1000000
```
